
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring03?serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: UserPro
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8089
version:  UserPro-mhmwww
