
spring:
  datasource:
    url: jdbc:mysql://db1:3306/spring03?serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: UserPro
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

version:  UserPro-mhmwww
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka,http://localhost:9999/eureka